CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(100),
    image_url VARCHAR(2048),
    stock_quantity INTEGER NOT NULL DEFAULT 0
);

-- Mock Data
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES
('Laptop Pro 15', 'High-performance laptop for professionals.', 1299.99, 'Electronics', 'https://placehold.co/300x300?text=Laptop+Pro', 50),
('Wireless Mouse', 'Ergonomic wireless mouse with long battery life.', 25.50, 'Accessories', 'https://placehold.co/300x300?text=Wireless+Mouse', 200),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard for gaming and typing.', 75.00, 'Accessories', 'https://placehold.co/300x300?text=Mechanical+Keyboard', 100),
('4K Monitor 27"', '27-inch 4K UHD monitor with vibrant colors.', 349.99, 'Electronics', 'https://placehold.co/300x300?text=4K+Monitor', 30),
('Coffee Maker Deluxe', 'Programmable coffee maker with thermal carafe.', 59.95, 'Appliances', 'https://placehold.co/300x300?text=Coffee+Maker', 75),
('Smart Watch Series X', 'Latest generation smart watch with health tracking.', 199.00, 'Wearables', 'https://placehold.co/300x300?text=Smart+Watch', 120),
('Bluetooth Headphones', 'Noise-cancelling over-ear Bluetooth headphones.', 89.99, 'Audio', 'https://placehold.co/300x300?text=Headphones', 150),
('USB-C Hub Adapter', 'Multi-port USB-C hub with HDMI, USB 3.0, and SD card reader.', 35.00, 'Accessories', 'https://placehold.co/300x300?text=USB-C+Hub', 80),
('Gaming Chair Ergo', 'Ergonomic gaming chair with lumbar support.', 250.00, 'Furniture', 'https://placehold.co/300x300?text=Gaming+Chair', 25),
('External SSD 1TB', 'Portable 1TB external solid state drive.', 110.50, 'Storage', 'https://placehold.co/300x300?text=External+SSD', 60),
('Gaming Laptop Ultra', 'Ultimate gaming laptop with high refresh rate.', 1999.99, 'Electronics', 'https://placehold.co/300x300?text=Gaming+Laptop', 30),
('Wireless Charger', 'Fast wireless charger for smartphones.', 19.99, 'Accessories', 'https://placehold.co/300x300?text=Wireless+Charger', 150),
('Portable Projector', 'Compact projector for home and travel.', 299.99, 'Electronics', 'https://placehold.co/300x300?text=Portable+Projector', 20),
('Smartphone X', 'Latest smartphone with advanced features.', 899.00, 'Electronics', 'https://placehold.co/300x300?text=Smartphone+X', 100),
('Fitness Tracker', 'Wearable fitness tracker with heart rate monitor.', 49.99, 'Wearables', 'https://placehold.co/300x300?text=Fitness+Tracker', 200),
('Bluetooth Speaker', 'Portable Bluetooth speaker with deep bass.', 79.99, 'Audio', 'https://placehold.co/300x300?text=Bluetooth+Speaker', 120),
('Smart Home Hub', 'Central hub for smart home devices.', 129.99, 'Home Automation', 'https://placehold.co/300x300?text=Smart+Home+Hub', 80),
('Electric Kettle', 'Fast boiling electric kettle with temperature control.', 39.99, 'Appliances', 'https://placehold.co/300x300?text=Electric+Kettle', 60),
('VR Headset', 'Immersive virtual reality headset.', 399.99, 'Gaming', 'https://placehold.co/300x300?text=VR+Headset', 25),
('Action Camera', 'Compact action camera for adventure filming.', 249.99, 'Cameras', 'https://placehold.co/300x300?text=Action+Camera', 40),
('Smart Thermostat', 'Wi-Fi enabled smart thermostat for energy savings.', 199.99, 'Home Automation', 'https://placehold.co/300x300?text=Smart+Thermostat', 70),
('Electric Toothbrush', 'Rechargeable electric toothbrush with timer.', 59.99, 'Health', 'https://placehold.co/300x300?text=Electric+Toothbrush', 150),
('Air Fryer', 'Healthy air fryer for quick cooking.', 89.99, 'Appliances', 'https://placehold.co/300x300?text=Air+Fryer', 90),
('Digital Camera', 'High-resolution digital camera for photography.', 499.99, 'Cameras', 'https://placehold.co/300x300?text=Digital+Camera', 15),
('Laptop Stand', 'Adjustable laptop stand for ergonomic use.', 29.99, 'Accessories', 'https://placehold.co/300x300?text=Laptop+Stand', 200),
('Noise Cancelling Earbuds', 'Wireless earbuds with noise cancellation.', 129.99, 'Audio', 'https://placehold.co/300x300?text=Noise+Cancelling+Earbuds', 100),
('Smart Light Bulb', 'Wi-Fi enabled smart light bulb.', 14.99, 'Home Automation', 'https://placehold.co/300x300?text=Smart+Light+Bulb', 300),
('Gaming Mouse', 'High precision gaming mouse with RGB lighting.', 59.99, 'Accessories', 'https://placehold.co/300x300?text=Gaming+Mouse', 80),
('Smart Lock', 'Keyless smart lock for home security.', 199.99, 'Home Automation', 'https://placehold.co/300x300?text=Smart+Lock', 50),
('Portable Battery Pack', 'High-capacity portable charger.', 39.99, 'Accessories', 'https://placehold.co/300x300?text=Portable+Battery+Pack', 150),
('Streaming Device', 'Device for streaming content on your TV.', 49.99, 'Electronics', 'https://placehold.co/300x300?text=Streaming+Device', 100),
('Smart Scale', 'Digital scale with body composition analysis.', 79.99, 'Health', 'https://placehold.co/300x300?text=Smart+Scale', 60),
('Electric Grill', 'Indoor electric grill for easy cooking.', 89.99, 'Appliances', 'https://placehold.co/300x300?text=Electric+Grill', 40),
('Wireless Earbuds', 'Compact wireless earbuds with great sound.', 79.99, 'Audio', 'https://placehold.co/300x300?text=Wireless+Earbuds', 150),
('Smart Refrigerator', 'Refrigerator with smart features and touchscreen.', 2499.99, 'Appliances', 'https://placehold.co/300x300?text=Smart+Refrigerator', 10),
('Home Security Camera', 'Wi-Fi enabled security camera for home.', 129.99, 'Home Security', 'https://placehold.co/300x300?text=Home+Security+Camera', 80),
('Digital Photo Frame', 'Wi-Fi enabled digital photo frame.', 99.99, 'Accessories', 'https://placehold.co/300x300?text=Digital+Photo+Frame', 70),
('Smartwatch Series Y', 'Advanced smartwatch with fitness tracking.', 249.99, 'Wearables', 'https://placehold.co/300x300?text=Smartwatch+Series+Y', 50),
('Cordless Vacuum Cleaner', 'Lightweight cordless vacuum for easy cleaning.', 199.99, 'Appliances', 'https://placehold.co/300x300?text=Cordless+Vacuum+Cleaner', 30),
('Electric Pressure Cooker', 'Multi-functional electric pressure cooker.', 89.99, 'Appliances', 'https://placehold.co/300x300?text=Electric+Pressure+Cooker', 40),
('Smart Air Purifier', 'Air purifier with smart features.', 199.99, 'Home Appliances', 'https://placehold.co/300x300?text=Smart+Air+Purifier', 20),
('Portable Bluetooth Keyboard', 'Compact Bluetooth keyboard for travel.', 49.99, 'Accessories', 'https://placehold.co/300x300?text=Portable+Bluetooth+Keyboard', 100),
('Smart Garden Kit', 'Indoor garden kit with smart features.', 129.99, 'Home & Garden', 'https://placehold.co/300x300?text=Smart+Garden+Kit', 30),
('Electric Wine Opener', 'Automatic wine opener for easy use.', 29.99, 'Appliances', 'https://placehold.co/300x300?text=Electric+Wine+Opener', 150),
('Smart Pet Feeder', 'Automatic pet feeder with scheduling.', 99.99, 'Pet Supplies', 'https://placehold.co/300x300?text=Smart+Pet+Feeder', 40),
('Digital Voice Recorder', 'Compact voice recorder for meetings.', 59.99, 'Electronics', 'https://placehold.co/300x300?text=Digital+Voice+Recorder', 80),
('Smartphone Stand', 'Adjustable stand for smartphones.', 19.99, 'Accessories', 'https://placehold.co/300x300?text=Smartphone+Stand', 200),
('Wireless Home Speaker', 'Home speaker with wireless connectivity.', 129.99, 'Audio', 'https://placehold.co/300x300?text=Wireless+Home+Speaker', 60),
('Smart Coffee Machine', 'Coffee machine with smart features.', 199.99, 'Appliances', 'https://placehold.co/300x300?text=Smart+Coffee+Machine', 25);